version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stockMarket:1:1"
    networks:
      - kafka-net
  app:
    build: ./backend
    command: flask --app ./api/main.py --debug run --host=0.0.0.0 --port 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - backend
  react:
    build: ./frontend
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - frontend
networks:
  kafka-net:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge